# Generated by Django 6.0.7 on 2026-08-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceroutehop',
            name='loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceroutehop',
            name='max_rtt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceroutehop',
            name='min_rtt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
