# Generated by Django 6.0.7 on 2026-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceroute', '0002_traceroutehop_loss_traceroutehop_max_rtt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WANStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wan_index', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='Unknown', max_length=20)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subnet_mask', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_server', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wan_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('connection_uptime', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv6_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv6_prefix', models.CharField(blank=True, max_length=64, null=True)),
                ('ipv6_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv6_primary_dns', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv6_secondary_dns', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WAN Status',
                'verbose_name_plural': 'WAN Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
