# Generated by Django 6.0.7 on 2026-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceroute', '0003_wanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LANStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lan_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('lan_mask', models.GenericIPAddressField(blank=True, null=True)),
                ('dhcp_enabled', models.BooleanField(default=False)),
                ('dhcp_start', models.GenericIPAddressField(blank=True, null=True)),
                ('dhcp_end', models.GenericIPAddressField(blank=True, null=True)),
                ('dhcp_lease_time', models.CharField(blank=True, max_length=50, null=True)),
                ('lan_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('num_clients', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LAN Status',
                'verbose_name_plural': 'LAN Status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpticalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_power', models.FloatField(blank=True, null=True)),
                ('rx_power', models.FloatField(blank=True, null=True)),
                ('tx_bias', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('optical_state', models.CharField(blank=True, max_length=20, null=True)),
                ('laser_bias_current', models.FloatField(blank=True, null=True)),
                ('tx_operating_current', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Optical Info',
                'verbose_name_plural': 'Optical Info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoIPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voip_state', models.CharField(blank=True, max_length=20, null=True)),
                ('sip_server', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_server', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_state', models.CharField(blank=True, max_length=50, null=True)),
                ('call_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('active_calls', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'VoIP Status',
                'verbose_name_plural': 'VoIP Status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WirelessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('bssid', models.CharField(blank=True, max_length=17, null=True)),
                ('channel', models.PositiveIntegerField(blank=True, null=True)),
                ('channel_width', models.CharField(blank=True, max_length=20, null=True)),
                ('security_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('tx_rate', models.FloatField(blank=True, null=True)),
                ('rx_rate', models.FloatField(blank=True, null=True)),
                ('associated_clients', models.PositiveIntegerField(blank=True, null=True)),
                ('wifi_state', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Wireless Status',
                'verbose_name_plural': 'Wireless Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
